var events = [
  {'Date': new Date(2020, 0, 4), 'Title': 'World Braille Day'},
  {'Date': new Date(2020, 0, 9), 'Title': 'NRI Day'},
  {'Date': new Date(2020, 0, 10), 'Title': 'World Hindi Day'},
  {'Date': new Date(2020, 0, 12), 'Title': 'National Youth Day'},
  {'Date': new Date(2020, 0, 15), 'Title': 'Army Day'},
  {'Date': new Date(2020, 0, 25), 'Title': 'National Voters Day'},
  {'Date': new Date(2020, 0, 26), 'Title': 'Índia\'s Republic Day,International Customs Day, World Leprosy Eradication Day'},
  {'Date': new Date(2020, 0, 27), 'Title': 'International Day of Commemoration'},
  {'Date': new Date(2020, 0, 30), 'Title': 'Martyrs\' Day'},

  {'Date': new Date(2020, 1, 2 ), 'Title': 'World Wetlands Day'},
  {'Date': new Date(2020, 1, 4  ), 'Title': 'World Cancer Day'},
  {'Date': new Date(2020, 1, 6  ), 'Title': 'International Day of Zero Tolerance to Female Genital Mutilation'},
  {'Date': new Date(2020, 1, 10), 'Title': 'National De-worming Day'},
  {'Date': new Date(2020, 1, 11), 'Title': 'International Dayof Women and girls in Science, Safer Internet Day'},
  {'Date': new Date(2020, 1, 12), 'Title': 'National productivity Day'},
  {'Date': new Date(2020, 1, 13), 'Title': 'World Radio Day, National Women\'s Day'},
  {'Date': new Date(2020, 1, 14), 'Title': 'Valentine Day'},
  {'Date': new Date(2020, 1, 20), 'Title': 'World Dayof Social Justice'},
  {'Date': new Date(2020, 1, 21), 'Title': 'International Mother Language Day'},
  {'Date': new Date(2020, 1, 24), 'Title': 'Central Excise Day'},
  {'Date': new Date(2020, 1, 28), 'Title': 'National Science Day'},

  {'Date': new Date(2020, 2, 1), 'Title': 'Zero Discrimination Day,World Civil Defence Day'},
  {'Date': new Date(2020, 2, 3), 'Title': 'World Wildlife Day,World Hearing Day'},
  {'Date': new Date(2020, 2, 4), 'Title': 'National Security Day'},
  {'Date': new Date(2020, 2, 8), 'Title': 'International Women\'s Day'},
  {'Date': new Date(2020, 2, 11), 'Title': 'No Smoking Day'},
  {'Date': new Date(2020, 2, 12), 'Title': 'World Kidney Day'},
  {'Date': new Date(2020, 2, 15), 'Title': 'World Consumer Rights Day'},
  {'Date': new Date(2020, 2, 18), 'Title': 'Ordnance Factories Day(India)'},
  {'Date': new Date(2020, 2, 20), 'Title': 'International Day of Happiness,World Sparrow Day'},
  {'Date': new Date(2020, 2, 21), 'Title': 'World Forestry Day, World Down Syndrome Day, World Poetry Day'},
  {'Date': new Date(2020, 2, 22), 'Title': 'World Day for Water'},
  {'Date': new Date(2020, 2, 23), 'Title': 'World Meteorological Day'},
  {'Date': new Date(2020, 2, 24), 'Title': 'World TB Day'},
  {'Date': new Date(2020, 2, 27), 'Title': 'World Theatre Day'},

  {'Date': new Date(2020, 3, 2), 'Title': 'World Autism Awareness Day'},
  {'Date': new Date(2020, 3, 4), 'Title': 'International Day for Mine Awareness'},
  {'Date': new Date(2020, 3, 5), 'Title': 'National Maritime Day'},
  {'Date': new Date(2020, 3, 7), 'Title': 'World Health Day'},
  {'Date': new Date(2020, 3, 10), 'Title': 'World Homeopathy Day'},
  {'Date': new Date(2020, 3, 11), 'Title': 'National Safe Motherhood Day,National Pet Day'},
  {'Date': new Date(2020, 3, 17), 'Title': 'World Haemophilia Day'},
  {'Date': new Date(2020, 3, 18), 'Title': 'World Heritage Day'},
  {'Date': new Date(2020, 3, 19), 'Title': 'World Liver Day'},
  {'Date': new Date(2020, 3, 21), 'Title': 'Secretaries\' Day, 	Civil Services Day'},
  {'Date': new Date(2020, 3, 22), 'Title': 'Earth Day'},
  {'Date': new Date(2020, 3, 23), 'Title': 'World Book and Copyright Day'},
  {'Date': new Date(2020, 3, 24), 'Title': 'National Panchayati Day'},
  {'Date': new Date(2020, 3, 25), 'Title': 'World Malaria Day'},
  {'Date': new Date(2020, 3, 26), 'Title': 'World Intellectual Property Day'},
  {'Date': new Date(2020, 3, 28), 'Title': 'World Day for Safety and Healthat Work, World Veterinary Day'},
  {'Date': new Date(2020, 3, 29), 'Title': 'International Dance Day'},
  {'Date': new Date(2020, 3, 30), 'Title': 'Ayushman Bharat Diwas'},

  {'Date': new Date(2020, 4, 1), 'Title': 'International Labour Day, Maharashtra Day'},
  {'Date': new Date(2020, 4, 3), 'Title':'Press Freedom Day, World Laughter Day'},
  {'Date': new Date(2020, 4, 5), 'Title':'World Asthma Day'},
  {'Date': new Date(2020, 4, 10), 'Title':'Mother\'s Day'},
  {'Date': new Date(2020, 4, 4), 'Title':'Coal Miners\' Day, International Firefighters Day'},
  {'Date': new Date(2020, 4, 7), 'Title':'World Athletics Day'},
  {'Date': new Date(2020, 4, 8), 'Title':'World Red Cross Day, World Thalassaemia Day'},
  {'Date': new Date(2020, 4, 11), 'Title':'National Technology Day'},
  {'Date': new Date(2020, 4, 12), 'Title':'National Nurse Day'},
  {'Date': new Date(2020, 4, 15), 'Title':'International Day of the Family'},
  {'Date': new Date(2020, 4, 17), 'Title':'World Telecommunication Day, World Hypertension Day'},
  {'Date': new Date(2020, 4, 18), 'Title':'World AIDS Vaccine Day, International Museum Day'},
  {'Date': new Date(2020, 4, 21), 'Title':'National Anti-terrorism Day'},
  {'Date': new Date(2020, 4, 22), 'Title':'International Day for Biological Diversity'},
  {'Date': new Date(2020, 4, 24), 'Title':'Commonwealth Day'},
  {'Date': new Date(2020, 4, 31), 'Title':'Anti-tobacco Day'},

  {'Date': new Date(2020, 5, 1), 'Title':'World Milk Day'},
  {'Date': new Date(2020, 5, 3), 'Title':'World Bicycle Day'},
  {'Date': new Date(2020, 5, 4), 'Title':'International Dayof Innocent Children Victims of Aggression'},
  {'Date': new Date(2020, 5, 5), 'Title':'World Environment Day'},
  {'Date': new Date(2020, 5, 21), 'Title':'Father\'s Day'},
  {'Date': new Date(2020, 5, 8), 'Title':'World Ocean Day'},
  {'Date': new Date(2020, 5, 12), 'Title':'Anti-child Labor Day'},
  {'Date': new Date(2020, 5, 13), 'Title':'International Albinism Awareness Day'},
  {'Date': new Date(2020, 5, 14), 'Title':'World Blood Donor Day'},
  {'Date': new Date(2020, 5, 20), 'Title':'World Refugee Day'},
  {'Date': new Date(2020, 5, 21), 'Title':'International Yoga Day'},
  {'Date': new Date(2020, 5, 23), 'Title':'United Nations Public Service Day'},
  {'Date': new Date(2020, 5, 26), 'Title':'International Day against Drug Abuse and Illicit Trafficking'},

 {'Date': new Date(2019, 6, 1), 'Title':'Doctor\'s Day'},
 {'Date': new Date(2019, 6, 6), 'Title':'World Zoonoses Day'},
 {'Date': new Date(2019, 6, 11), 'Title':'World Population Day'},
 {'Date': new Date(2019, 6, 17), 'Title':'World Day for International Justice'},
 {'Date': new Date(2019, 6, 18), 'Title':'International Nelson Mandela Day'},
 {'Date': new Date(2019, 6, 28), 'Title':'World Hepatitis Day'},

 {'Date': new Date(2019, 7, 6), 'Title': 'Hiroshima Day'},
 {'Date': new Date(2019, 7, 9), 'Title': 'Quit India Day,Nagasaki Day, International Day of te World\'s Indigenous Peoples'},
 {'Date': new Date(2019, 7, 15), 'Title': 'Indian Independence Day, Rakhsha Bandhan'},
 {'Date': new Date(2019, 7, 12), 'Title': 'International Youth Day'},
 {'Date': new Date(2019, 7, 19), 'Title': 'Photography Day, World Humanitarian Day'},
 {'Date': new Date(2019, 7, 29), 'Title': 'National Sports Day'},

 {'Date': new Date(2019, 8, 1), 'Title': 'Teej, Onam'},
 {'Date': new Date(2019, 8, 2), 'Title': 'Coconut Day, Ganesh Chaturthi'},
 {'Date': new Date(2019, 8, 3), 'Title': 'Nuakhai'},
 {'Date': new Date(2019, 8, 5), 'Title': 'Teacher\'s Day, Sanskrit Day'},
 {'Date': new Date(2019, 8, 8), 'Title': 'International Literacy Day'},
 {'Date': new Date(2019, 8, 13), 'Title': 'Mahalaya'},
 {'Date': new Date(2019, 8, 14), 'Title': 'Hindi Diwas'},
 {'Date': new Date(2019, 8, 15), 'Title': 'Engineer\'s Day, International Day of Democracy'},
 {'Date': new Date(2019, 8, 16), 'Title': 'World Ozone Day, International Day for Preservation'},
 {'Date': new Date(2019, 8, 21), 'Title': 'Alzheimer\'s Day, Day for Peace and Non-violence'},
 {'Date': new Date(2019, 8, 22), 'Title': 'Rose Day(Welfare of Cancer patients), World Rivers Day'},
 {'Date': new Date(2019, 8, 23), 'Title': 'International Dayof Sign Language'},
 {'Date': new Date(2019, 8, 26), 'Title': 'Day of Deaf, World Contraception Day'},
 {'Date': new Date(2019, 8, 27), 'Title': 'World Tourism Day, World Maritime Day'},
 {'Date': new Date(2019, 8, 29), 'Title': 'World Heart Day'},
 {'Date': new Date(2019, 8, 30), 'Title': 'International Translation Day'},

 {'Date': new Date(2019, 9, 1), 'Title': 'International Day for Elderly'},
 {'Date': new Date(2019, 9, 2), 'Title': 'Gandhi Jayanti,International Day of Non-violence'},
 {'Date': new Date(2019, 9, 7), 'Title': 'World habitat Day'},
 {'Date': new Date(2019, 9, 4), 'Title': 'World Animal Welfare Day'},
 {'Date': new Date(2019, 9, 8), 'Title': 'Indian Air Force Day, Dussehra'},
 {'Date': new Date(2019, 9, 9), 'Title': 'World Post Office Day'},
 {'Date': new Date(2019, 9, 10), 'Title': 'National Post Day, World Mental Health Day, World Sight Day'},
 {'Date': new Date(2019, 9, 11), 'Title': 'National Girl Child Day'},
 {'Date': new Date(2019, 9, 13), 'Title': 'UN International Day for Natural Disaster Reduction'},
 {'Date': new Date(2019, 9, 14), 'Title': 'World Standards Day'},
 {'Date': new Date(2019, 9, 15), 'Title': 'World Students Day, World White Cane Day(guiding the blind)'},
 {'Date': new Date(2019, 9, 16), 'Title': 'World Food Day'},
 {'Date': new Date(2019, 9, 24), 'Title': 'UN Day, World Development Information Day'},
 {'Date': new Date(2019, 9, 30), 'Title': 'World Thrift Day'},
 {'Date': new Date(2019, 9, 27), 'Title': 'Diwali'},
 {'Date': new Date(2019, 9, 31), 'Title': 'National Unity Day'}, 

 {'Date': new Date(2019, 10, 5), 'Title': 'World tsunami Day'},
 {'Date': new Date(2019, 10, 7), 'Title': 'National Cancer Awareness Day'},
 {'Date': new Date(2019, 10, 9), 'Title': 'Legal Services Day'},
 {'Date': new Date(2019, 10, 14), 'Title': 'Children\'s Day, Diabetes Day'},
 {'Date': new Date(2019, 10, 17), 'Title': 'National Epilepsy Day'},
 {'Date': new Date(2019, 10, 20), 'Title': 'Africa Industrialization Day'},
 {'Date': new Date(2019, 10, 21), 'Title': 'World teelvision Day'},
 {'Date': new Date(2019, 10, 29), 'Title': 'International Day of Solidarity with Palestinian People'},

 {'Date': new Date(2019, 11, 1), 'Title': 'World AIDS Day'},
 {'Date': new Date(2019, 11, 2), 'Title': 'National Pollution Control Day'},
 {'Date': new Date(2019, 11, 3), 'Title': 'World Day of the Handicapped'},
 {'Date': new Date(2019, 11, 4), 'Title': 'Indian Navy Day'},
 {'Date': new Date(2019, 11, 7), 'Title': 'Indian Armed Forces Flag Day'},
 {'Date': new Date(2019, 11, 10), 'Title': 'Human Rights Day, International Children\'s Day of Broadcasting'},
 {'Date': new Date(2019, 11, 11), 'Title': 'International Mountain Day'},
 {'Date': new Date(2019, 11, 14), 'Title': 'World Energy Conservation Day'},
 {'Date': new Date(2019, 11, 16), 'Title': 'Vijay Diwas'},
 {'Date': new Date(2019, 11, 18), 'Title': 'Minorities Rights Day(India)'},
 {'Date': new Date(2019, 11, 22), 'Title': 'National Mathematics Day'},
 {'Date': new Date(2019, 11, 23), 'Title': 'Kisan Diwas'},
 {'Date': new Date(2019, 11, 24), 'Title': 'National Consumers Day'},
 {'Date': new Date(2019, 11, 25), 'Title': 'Christmas Day'},

];
var settings = {};
var element = document.getElementById('caleandar');
caleandar(element, events, settings);
